### PR TITLE
Update RouteCollectionInterface.php

### PR DESCRIPTION
**Pull request by xepozz**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️

### CODE REVIEW

**Comment by rustamwin** [comment]
Also could you fix `getRouteTree`?

**Comment by xepozz** [comment]
> getRouteTree

`getRouteTree` returns tree of strings, e.g.:
```
- /api
--- /user
--- /article
```

**Comment by rustamwin** [comment]
I meant the missing argument. https://github.com/yiisoft/router/blob/a586e87793c695468efb986d5c87a0431513afbe/src/RouteCollection.php#L65

**Comment by samdark** [comment]
Thanks!

**Pull request merged**
