### PR TITLE
Router fix

### PR DESCRIPTION
**Pull request by yiiliveext**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  |❌
| Breaks BC?    | ❌
| Tests pass?   | ✔️

Fix codestyle and Route handler logical error

### CODE REVIEW

**Comment by yiiliveext** [comment]
It is strange. According to PSR-12 (https://www.php-fig.org/psr/psr-12/#8-anonymous-classes) 
```php 
new class implements MiddlewareInterface {
}
```
is the right way. But continuous-integration/styleci/pr thinks otherwise.

**Comment by roxblnfk** [comment]
> This is strange. According to PSR-12 (https://www.php-fig.org/psr/psr-12/#8-anonymous-classes)
> 
> ```
> new class implements MiddlewareInterface {
> }
> ```
> 
> is the right way. But continuous-integration/styleci/pr thinks otherwise.

psr:
`new class implements MiddlewareInterface`
styleci:
`new class() implements MiddlewareInterface`
linter:
`new class implements MiddlewareInterface` or `new class () implements MiddlewareInterface`

( ╯°□°)╯┻┻

But PSR could be adjusted soon: https://github.com/php-fig/fig-standards/pull/1206

**Comment by samdark** [comment]
Good catch about the error.

**Comment by samdark** [comment]
Thanks!

**Pull request merged**
